# Generated by Django 3.0.8 on 2020-07-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_auto_20200723_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
